### ISSUE TITLE
the download button is not displayed correctly

### ISSUE THREAD

**Issue by cyanmint** [PurpleI2P/purplei2p.github.io#2]
it should have shown "Downloads", but it turned out to be "header.dl-btn"
![Capture.PNG](https://user-images.githubusercontent.com/20249732/28996324-d3dce744-79ed-11e7-9435-f3a8941504f2.PNG)
i'm using firefox.

**Comment by l-n-s** [comment]
I've changed l10n framework. Check again.

**Comment by l-n-s** [comment]
k, seems to be fixed

**Comment by ghost** [comment]
Mozilla Firefox 91.0
![issue](https://user-images.githubusercontent.com/67541260/129458559-30d9879a-0700-4c6c-a8af-19e93bdbc5b7.png)
@orignal

**Comment by ghost** [comment]
Chromium 92.0.4515.131 is **OK**

**Comment by r4sas** [comment]
> Mozilla Firefox 91.0
> ![issue](https://user-images.githubusercontent.com/67541260/129458559-30d9879a-0700-4c6c-a8af-19e93bdbc5b7.png)
> @orignal

nojs?

**Comment by ghost** [comment]
@r4sas
I found:
```
intl.accept_languages =
```
if not
https://github.com/PurpleI2P/purplei2p.github.io/blob/aa95f9df86e00dd3adc7c2ce72cc228fdd753244/locales/data.ini#L1
or
https://github.com/PurpleI2P/purplei2p.github.io/blob/aa95f9df86e00dd3adc7c2ce72cc228fdd753244/locales/data.ini#L23
But if set **en-US** then OK, if **ru** then OK. And If set **en** then FAIL, if **ru-RU** then OK.
Bug only with the Download button.

**Comment by r4sas** [comment]
Oh, I got it.
Will think how to fix fallback to english, if language is not found in localization file.

**Comment by r4sas** [comment]
@HKAlexandrovich must be fixed now.
